import { releaseLog } from "./release-log";

export type EditorRelease = { version:string; title:string; changes:readonly string[] };

const recent:EditorRelease[]=[
  {version:"v0.68",title:"Reliable image editing, presets and protective rims",changes:["Fixed the hidden Advanced Background Removal state that appeared after Separate as Layers closed Edit Image.","Made Separate as Layers use the currently cropped and edited image together with its corrected canvas geometry.","Cleared every related image and background modal state after separated layers are created.","Fixed background presets using the wrong selected layer history when Quick Fix targeted another layer.","Rebuilt Add Rim as a physical protective expansion that keeps available edge pixels and uses white—not black—as its only fallback color.","Expanded the layer frame with the rim so new pixels are not clipped.","Applied alpha cleanup, smoothing and fresh safety analysis after rim creation.","Made Quick Fix replace the prior background-removal result instead of stacking repeated rims.","Added Apply Preset as the third Edit Image tab.","Added vertically arranged visual Default, Add Rim and Black-and-White Text presets inside Edit Image.","Made in-window presets respect crop and erase work already visible in the editor.","Repositioned and resized Undo, Reset, Alpha and Optimize Alpha immediately beside the close button.","Improved the visible alpha-mask preview and stopped Optimize Alpha from silently changing the Alpha view toggle.","Made Advanced Background Removal wait for the current preview render before its Apply action is available.","Added global pointer release, cancellation and focus-loss cleanup for stuck marquee selection rectangles."]},
  {version:"v0.67",title:"Reliable Image on Shape selection",changes:["Kept Image on Shape selection mode in a persistent interaction reference so selecting another layer cannot silently cancel it.","Captured Layers-panel image clicks before normal layer selection, preventing the chosen source from merely becoming selected.","Added a visible canvas instruction and copy cursor while the editor is waiting for an image.","Kept Escape cancellation synchronized with both the visible mode and its interaction state."]},
  {version:"v0.66",title:"Editable Image on Shape",changes:["Renamed Image in Shape to Image on Shape and changed it from a file picker into a canvas-and-Layers selection workflow.","Restricted shape placement to regular raster image layers so cutouts, shapes and generated stroke layers cannot be selected accidentally.","Kept the chosen image at its existing canvas position and size while displaying only its intersection with the shape.","Moved the source image into an editable Image on Shape layer style instead of permanently flattening or discarding it.","Added an independent image frame for repositioning and proportionally resizing the image inside the shape.","Made the embedded image travel, scale and rotate naturally with its parent shape.","Added visibility and removal controls to the Image on Shape style.","Restored the original image layer at its previous position and dimensions when the style is removed.","Kept shape color changes independent from the embedded image so eyedropper-picked fills continue to work.","Added Escape and repeat-click cancellation for the image-selection workflow."]},
  {version:"v0.65",title:"Raster-aware warnings and embedded background editing",changes:["Realigned cut-safety triangles and added hover feedback that clearly identifies them as clickable controls.","Split warning actions by layer type: cutouts open Edit Cutout while raster images open Edit Image.","Added Quick Fix: Add Rim for raster warnings and connected it directly to the Add Rim background-removal preset.","Added Edit Image and Advanced Background Removal tabs inside the same image editor window.","Kept Undo, Reset, Alpha and Optimize Alpha available in the image editor header across both tabs.","Limited Separate as Layers to the standard Edit Image tab.","Made Stroke and Fill Gaps disable as complete, visually consistent groups when the selection is incompatible.","Restyled the Layers heading to match the Stroke and Fill Gaps panel hierarchy.","Removed built-in whitespace from generated shape SVG bounds.","Changed shape hit testing so transparent portions of a shape layer no longer select it."]},
  {version:"v0.64",title:"Actionable safety warnings and cutout workspace tabs",changes:["Made cut-safety warning icons clickable from both the canvas measurement label and Layers panel.","Added a Cut Safety dialog with the detected reason, Cancel, Edit Cutout and Quick Fix actions.","Added one-click contour cleanup and automatic safety re-analysis through Quick Fix.","Moved the Layers warning icon beneath the visibility control.","Added Bring to Front, Send to Back and Hide to the floating layer toolbar.","Added Cutout Edit and Stroke & Fill Gaps tabs to Edit Cutout.","Renamed Bridge and Erase to Add Brush and Eraser Brush and redesigned the tool grid.","Expanded the Fix the Edges control across both columns and made brush sizing substantially wider.","Moved Crop beneath Crop Canvas and compacted the panel to avoid unnecessary scrolling.","Added a visible contour to areas painted with Add Brush.","Rendered vector layers with scalable strokes on both the main canvas and Edit Cutout preview.","Loaded the signed-in Google profile picture into My Account and made outside clicks dismiss the panel.","Refreshed Page Setup, My Projects, Open and Overwrite icon treatments.","Removed unused horizontal padding around Background Removal and Make Cutout preview cards."]},
  {version:"v0.63",title:"Cut safety analysis and cutout presets",changes:["Added physical 2 mm cut-safety analysis for thin connections, tiny positive islands and tiny enclosed gaps.","Marked risky selections and Layers cards in red with a visible warning icon.","Added a critical confirmation before exporting risky SVG files.","Applied the same safety analysis to background-removed raster images and vector cutouts.","Raised Edit Cutout zoom to 1000% and made SVG preview strokes scale with the artwork for crisp inspection.","Changed Make Cutout into a visual preset dialog.","Added Smooth Cutout, Detailed Cutout and Advanced Cutout Edit workflows.","Added the supplied detailed and smooth cutout preview artwork.","Enlarged both Cutout and Remove Background preset dialogs for clearer preview comparison."]},
  {version:"v0.62",title:"Safer project transitions and editor footer tools",changes:["Rebuilt overwrite and project-transition dialogs with editor-scale typography and consistent spacing.","Made the main Save update only mutable project fields and added a safe identity fallback for older saved projects.","Added a New Project confirmation even when the current project is already saved.","Displayed Saved as a disabled action for clean projects, alongside Save As and OK.","Added Open saved projects beneath Choose an image on an empty canvas.","Exposed icon-only Open, Overwrite and Delete actions on collapsed project cards.","Moved Separate as Layers into the bottom action bar in both Edit Image and Edit Cutout.","Moved Smooth to the lower-left Edit Cutout action bar and relocated the image editor undo hint."]},
  {version:"v0.61",title:"Scale-stable contours and calmer project feedback",changes:["Added a dedicated Smooth action inside Edit Cutout for reducing excess contour points before Apply Edit.","Made repeated smoothing progressively stronger while preserving sharp direction changes.","Normalized tracing resolution against the layer's physical width so small and large designs receive consistent curve density.","Kept My Projects content cached and visible while fresh cloud data loads in the background.","Changed saving feedback to show Saving first, then Saved with a two-second countdown.","Allowed the saving notice to be dismissed without interrupting the background upload.","Rebuilt project cards with smaller typography, correctly fitted previews and downward-only expansion.","Gave the project list a stable viewport so expanding one project pushes later projects down instead of compressing its content."]},
  {version:"v0.60",title:"Reliable project saving and batch cutouts",changes:["Converted every compatible selected image into a Cricut-ready cutout in one operation.","Added Save Project and Save As Project directly inside My Projects.","Added a visible two-second saved confirmation with an immediate OK action.","Changed project rows into expandable cards so an accidental click no longer replaces the canvas.","Added compact project-wide thumbnails assembled from every visible layer.","Added individual layer previews, layer counts, project size and last-saved time to each project.","Added an explicit loading state while cloud projects are being retrieved.","Added save-before-open and save-before-new safeguards for canvases with unsaved work.","Added a separate overwrite confirmation before replacing an existing saved project."]},
  {version:"v0.59",title:"Cake Topper Maker identity and editor dev log",changes:["Renamed the editor workspace to Cake Topper Maker.","Turned the workspace version label into a clickable, scrollable development log.","Expanded releases into individual fixes and ordered the complete history newest first."]},
  {version:"v0.58",title:"Editor modal stability",changes:["Fixed the missing Layers icon import that crashed Edit Image and Edit Cutout when opened.","Rebuilt and validated both editor routes before deployment."]},
  {version:"v0.57",title:"Smooth Cutout v5 and island separation",changes:["Limited automatic empty-border trimming to PNG files; JPG files are left untouched.","Captured Chrome wheel events directly on the canvas so zoom no longer scrolls the document at the same time.","Kept cursor-anchored zoom correct across portrait, landscape and full-page modes.","Restored the dark contour after Fix the Edges modifies alpha pixels.","Moved edge re-vectorization to Apply Edit and run it only when an edge was actually fixed.","Added a dedicated, toggleable Crop mode to Edit Cutout.","Added Separate as Layers to both image and cutout editors.","Detected disconnected alpha islands and previewed every future layer in a different color.","Added explicit Cancel and Create Layers confirmation actions before replacing the source layer."]},
  {version:"v0.56",title:"Precision cutout editing feedback",changes:["Raised the main canvas maximum zoom to 700%.","Changed the Fix the Edges cursor from an oval SVG marker to a true circular overlay.","Displayed the selected physical alpha edge in red instead of painting the whole brush corridor.","Displayed the completed edge in green for one second before returning to its normal contour.","Added automatic PNG whitespace bounds detection when files enter the canvas."]},
  {version:"v0.55",title:"Cricut-optimized Smooth Cutout v4",changes:["Corrected VTracer spliceThreshold from 4 to its intended 45-degree curve split threshold.","Reduced thousands of tiny cutting movements by joining compatible curve runs.","Enabled the strongest SVG path cleanup and coordinate compaction.","Balanced curve simplification against preservation of long banner arcs and sharp corners."]},
  {version:"v0.54",title:"Google authentication repair",changes:["Added a cryptographically random nonce to Google One Tap.","Sent the SHA-256 nonce to Google and its original value to Supabase so validation succeeds.","Enabled the FedCM-compatible Google prompt flow."]},
  {version:"v0.53",title:"Visible sign-in diagnostics",changes:["Stopped silently swallowing Supabase authentication errors.","Added a persistent, readable sign-in error message to the landing page.","Required a real Supabase session before navigating to the protected editor."]},
  {version:"v0.52",title:"Landing-to-editor session flow",changes:["Changed every Open Editor call-to-action to check the current session.","Unauthenticated editor actions now open Google sign-in instead of bouncing through login=required.","Authenticated actions continue directly to /editor."]},
  {version:"v0.51",title:"Image clipping masks for shapes",changes:["Added Image in Shape for native vector shapes.","Allowed the placed image to be scaled and positioned while remaining clipped to its shape.","Added eyedrop color sampling for shape fills."]},
  {version:"v0.50",title:"Background history and geometry recovery",changes:["Reopened Advanced Background Removal from the last applied settings instead of starting over.","Remembered removed background colors for later edge expansion.","Restored original layer bounds when a background-removal step is removed.","Expanded layer bounds when edge refinement adds pixels outside the previous frame."]},
  {version:"v0.49",title:"Cutout interaction refinements",changes:["Added repeated-click cycling through overlapping layers.","Reset overlap cycling whenever the pointer moves.","Allowed crop handles in Edit Image to expand the canvas outward.","Made Edit Cutout tools toggleable and start with no active tool.","Strengthened trajectory-based Fix the Edges corrections."]},
  {version:"v0.48",title:"Background removal preset dialog",changes:["Replaced the background-removal chevron with a standalone visual preset dialog.","Added Default Image, Add Rim and Black-and-White Text removal presets.","Added 2 px feathering to image presets for softer Print Then Cut edges.","Reworked zoom controls with editable percentage, Center and Calibrate actions."]},
  {version:"v0.47",title:"Alpha cleanup and physical calibration",changes:["Added Optimize Alpha to remove tiny exterior islands and fill tiny interior holes.","Added adjustable Edge Smooth for reducing blade-path pixel noise.","Made 100% zoom respect saved physical screen calibration.","Added fine 0.1% calibration controls and one-direction ruler resizing."]},
  {version:"v0.46",title:"Page, selection and editing workflow",changes:["Added Page Setup with portrait, landscape and 100 × 100 cm full canvas modes.","Added Save, Save As and New Project as separate actions.","Changed marquee selection to hit visible pixels rather than empty layer bounds.","Added erase and lasso erase to Edit Image.","Added connected-area brush and multi-color eyedrop background removal.","Added grouped movement constraints and complete layer thumbnails."]},
  {version:"v0.45",title:"Landing page product story",changes:["Built the Ariana is ONE prompt-to-cake case study.","Redesigned product highlights around real Cricut tasks.","Added the technical terminal-style development history.","Fixed landing-page scrolling and editor navigation."]},
  {version:"v0.44",title:"Targeted contour repair",changes:["Added Fix the Edges for local contour correction.","Used the selected stroke endpoints and trajectory to preserve the intended curve.","Added popup zoom and pan plus a 400% editing zoom range.","Added grid visibility and compact background-removal controls."]},
];

export const editorDevLog:readonly EditorRelease[]=[...recent,...[...releaseLog].reverse().map(([version,title,text])=>({version,title,changes:[text]}))];
export const EDITOR_VERSION=recent[0].version;
