import { releaseLog } from "./release-log";

export type EditorRelease = { version:string; title:string; changes:readonly string[] };

const recent:EditorRelease[]=[
  {version:"v0.61",title:"Scale-stable contours and calmer project feedback",changes:["Added a dedicated Smooth action inside Edit Cutout for reducing excess contour points before Apply Edit.","Made repeated smoothing progressively stronger while preserving sharp direction changes.","Normalized tracing resolution against the layer's physical width so small and large designs receive consistent curve density.","Kept My Projects content cached and visible while fresh cloud data loads in the background.","Changed saving feedback to show Saving first, then Saved with a two-second countdown.","Allowed the saving notice to be dismissed without interrupting the background upload.","Rebuilt project cards with smaller typography, correctly fitted previews and downward-only expansion.","Gave the project list a stable viewport so expanding one project pushes later projects down instead of compressing its content."]},
  {version:"v0.60",title:"Reliable project saving and batch cutouts",changes:["Converted every compatible selected image into a Cricut-ready cutout in one operation.","Added Save Project and Save As Project directly inside My Projects.","Added a visible two-second saved confirmation with an immediate OK action.","Changed project rows into expandable cards so an accidental click no longer replaces the canvas.","Added compact project-wide thumbnails assembled from every visible layer.","Added individual layer previews, layer counts, project size and last-saved time to each project.","Added an explicit loading state while cloud projects are being retrieved.","Added save-before-open and save-before-new safeguards for canvases with unsaved work.","Added a separate overwrite confirmation before replacing an existing saved project."]},
  {version:"v0.59",title:"Cake Topper Maker identity and editor dev log",changes:["Renamed the editor workspace to Cake Topper Maker.","Turned the workspace version label into a clickable, scrollable development log.","Expanded releases into individual fixes and ordered the complete history newest first."]},
  {version:"v0.58",title:"Editor modal stability",changes:["Fixed the missing Layers icon import that crashed Edit Image and Edit Cutout when opened.","Rebuilt and validated both editor routes before deployment."]},
  {version:"v0.57",title:"Smooth Cutout v5 and island separation",changes:["Limited automatic empty-border trimming to PNG files; JPG files are left untouched.","Captured Chrome wheel events directly on the canvas so zoom no longer scrolls the document at the same time.","Kept cursor-anchored zoom correct across portrait, landscape and full-page modes.","Restored the dark contour after Fix the Edges modifies alpha pixels.","Moved edge re-vectorization to Apply Edit and run it only when an edge was actually fixed.","Added a dedicated, toggleable Crop mode to Edit Cutout.","Added Separate as Layers to both image and cutout editors.","Detected disconnected alpha islands and previewed every future layer in a different color.","Added explicit Cancel and Create Layers confirmation actions before replacing the source layer."]},
  {version:"v0.56",title:"Precision cutout editing feedback",changes:["Raised the main canvas maximum zoom to 700%.","Changed the Fix the Edges cursor from an oval SVG marker to a true circular overlay.","Displayed the selected physical alpha edge in red instead of painting the whole brush corridor.","Displayed the completed edge in green for one second before returning to its normal contour.","Added automatic PNG whitespace bounds detection when files enter the canvas."]},
  {version:"v0.55",title:"Cricut-optimized Smooth Cutout v4",changes:["Corrected VTracer spliceThreshold from 4 to its intended 45-degree curve split threshold.","Reduced thousands of tiny cutting movements by joining compatible curve runs.","Enabled the strongest SVG path cleanup and coordinate compaction.","Balanced curve simplification against preservation of long banner arcs and sharp corners."]},
  {version:"v0.54",title:"Google authentication repair",changes:["Added a cryptographically random nonce to Google One Tap.","Sent the SHA-256 nonce to Google and its original value to Supabase so validation succeeds.","Enabled the FedCM-compatible Google prompt flow."]},
  {version:"v0.53",title:"Visible sign-in diagnostics",changes:["Stopped silently swallowing Supabase authentication errors.","Added a persistent, readable sign-in error message to the landing page.","Required a real Supabase session before navigating to the protected editor."]},
  {version:"v0.52",title:"Landing-to-editor session flow",changes:["Changed every Open Editor call-to-action to check the current session.","Unauthenticated editor actions now open Google sign-in instead of bouncing through login=required.","Authenticated actions continue directly to /editor."]},
  {version:"v0.51",title:"Image clipping masks for shapes",changes:["Added Image in Shape for native vector shapes.","Allowed the placed image to be scaled and positioned while remaining clipped to its shape.","Added eyedrop color sampling for shape fills."]},
  {version:"v0.50",title:"Background history and geometry recovery",changes:["Reopened Advanced Background Removal from the last applied settings instead of starting over.","Remembered removed background colors for later edge expansion.","Restored original layer bounds when a background-removal step is removed.","Expanded layer bounds when edge refinement adds pixels outside the previous frame."]},
  {version:"v0.49",title:"Cutout interaction refinements",changes:["Added repeated-click cycling through overlapping layers.","Reset overlap cycling whenever the pointer moves.","Allowed crop handles in Edit Image to expand the canvas outward.","Made Edit Cutout tools toggleable and start with no active tool.","Strengthened trajectory-based Fix the Edges corrections."]},
  {version:"v0.48",title:"Background removal preset dialog",changes:["Replaced the background-removal chevron with a standalone visual preset dialog.","Added Default Image, Add Rim and Black-and-White Text removal presets.","Added 2 px feathering to image presets for softer Print Then Cut edges.","Reworked zoom controls with editable percentage, Center and Calibrate actions."]},
  {version:"v0.47",title:"Alpha cleanup and physical calibration",changes:["Added Optimize Alpha to remove tiny exterior islands and fill tiny interior holes.","Added adjustable Edge Smooth for reducing blade-path pixel noise.","Made 100% zoom respect saved physical screen calibration.","Added fine 0.1% calibration controls and one-direction ruler resizing."]},
  {version:"v0.46",title:"Page, selection and editing workflow",changes:["Added Page Setup with portrait, landscape and 100 × 100 cm full canvas modes.","Added Save, Save As and New Project as separate actions.","Changed marquee selection to hit visible pixels rather than empty layer bounds.","Added erase and lasso erase to Edit Image.","Added connected-area brush and multi-color eyedrop background removal.","Added grouped movement constraints and complete layer thumbnails."]},
  {version:"v0.45",title:"Landing page product story",changes:["Built the Ariana is ONE prompt-to-cake case study.","Redesigned product highlights around real Cricut tasks.","Added the technical terminal-style development history.","Fixed landing-page scrolling and editor navigation."]},
  {version:"v0.44",title:"Targeted contour repair",changes:["Added Fix the Edges for local contour correction.","Used the selected stroke endpoints and trajectory to preserve the intended curve.","Added popup zoom and pan plus a 400% editing zoom range.","Added grid visibility and compact background-removal controls."]},
];

export const editorDevLog:readonly EditorRelease[]=[...recent,...[...releaseLog].reverse().map(([version,title,text])=>({version,title,changes:[text]}))];
export const EDITOR_VERSION=recent[0].version;
