"use client";
import {useEffect,useRef,useState} from "react";
import {ArrowRight,Check,Layers3,Scissors,Sparkles,WandSparkles} from "lucide-react";
import type {Session} from "@supabase/supabase-js";
import {supabase} from "./lib/supabase";
import {releaseLog} from "./release-log";
import "./landing.css";import "./landing-v31.css";import "./landing-v44.css";import "./landing-v45.css";import "./landing-v46.css";
declare global{interface Window{google?:{accounts:{id:{initialize(options:{client_id:string;callback:(response:{credential:string})=>void;auto_select?:boolean;nonce?:string;use_fedcm_for_prompt?:boolean}):void;renderButton(element:HTMLElement,options:Record<string,string|number>):void;prompt():void}}}}}
const highlights=[
  [WandSparkles,"Free background removal","Remove the background you choose with edge refinement, color erasing, sensitivity, keep/remove brushes and speckle cleanup."],
  [Scissors,"Perfect cutouts","Convert generated artwork into cut-ready geometry for the cardstock colors and material layers you selected."],
  [Layers3,"Size in control","Set the final physical dimensions before the design reaches Cricut Design Space."],
  [Sparkles,"Add stroke","Generate backing-card and acetate support areas at an exact width around the original design."],
  [Check,"Get rid of small gaps","Fill tiny enclosed holes that would otherwise become fragile, unnecessary pieces on the cutting mat."],
  [WandSparkles,"Image editing. No Photoshop.","Crop, upscale and prepare raster artwork without opening a professional photo editor."],
  [Scissors,"SVG editing. No Illustrator.","Crop, bridge, erase, repair contours and export vectors without learning a full vector suite."],
] as const;
const moduleFor=(n:number)=>n>40?"VECTOR_EDIT":n>33?"TRACE_PIPELINE":n>28?"PLATFORM":n>22?"CANVAS_TOOLS":n>17?"MODIFIER_STACK":n>12?"RENDER_EXPORT":n>7?"INTERACTION":"FOUNDATION";
export default function LandingPage(){const[session,setSession]=useState<Session|null>(null),[busy,setBusy]=useState(false),[authError,setAuthError]=useState("");const googleButton=useRef<HTMLDivElement>(null);
useEffect(()=>{void supabase.auth.getSession().then(({data})=>setSession(data.session));const{data}=supabase.auth.onAuthStateChange((_e,next)=>setSession(next));return()=>data.subscription.unsubscribe()},[]);
useEffect(()=>{if(session)return;const clientId=process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID||"769733103078-1ifg8p2nqdfsukf0m3as9ilcfggcte2j.apps.googleusercontent.com";const setup=async()=>{if(!window.google||!googleButton.current)return;const nonce=btoa(String.fromCharCode(...crypto.getRandomValues(new Uint8Array(32))));const hash=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(nonce));const hashedNonce=Array.from(new Uint8Array(hash)).map(byte=>byte.toString(16).padStart(2,"0")).join("");window.google.accounts.id.initialize({client_id:clientId,auto_select:false,nonce:hashedNonce,use_fedcm_for_prompt:true,callback:async({credential})=>{setBusy(true);setAuthError("");try{const{data,error}=await supabase.auth.signInWithIdToken({provider:"google",token:credential,nonce});if(error)throw error;if(!data.session)throw new Error("Google sign-in completed, but no session was created.");setSession(data.session);window.location.assign("/editor")}catch(error){setAuthError(error instanceof Error?error.message:"Google sign-in could not be completed.");setBusy(false)}}});googleButton.current.replaceChildren();window.google.accounts.id.renderButton(googleButton.current,{type:"standard",theme:"outline",size:"large",shape:"pill",text:"continue_with",logo_alignment:"left",width:238})};const old=document.querySelector<HTMLScriptElement>('script[src="https://accounts.google.com/gsi/client"]');if(old)window.google?void setup():old.addEventListener("load",()=>void setup(),{once:true});else{const s=document.createElement("script");s.src="https://accounts.google.com/gsi/client";s.async=true;s.defer=true;s.onload=()=>void setup();s.onerror=()=>setAuthError("Google sign-in could not be loaded. Please refresh the page and try again.");document.head.appendChild(s)}},[session]);
const signIn=()=>{setAuthError("");setBusy(true);if(window.google)window.google.accounts.id.prompt();else window.setTimeout(signIn,250);window.setTimeout(()=>setBusy(false),3000)};
const editorAction=(className:string,label:string)=>session?<a className={className} href="/editor">{label} <ArrowRight/></a>:<button className={className} type="button" onClick={signIn} disabled={busy}>{busy?"Connecting…":label} <ArrowRight/></button>;
return <main className="story-site v46">{authError&&<div role="alert" style={{position:"fixed",zIndex:9999,top:76,left:"50%",transform:"translateX(-50%)",maxWidth:620,width:"calc(100% - 32px)",padding:"14px 18px",borderRadius:12,background:"#fff1f2",border:"1px solid #fecdd3",color:"#9f1239",fontWeight:700,boxShadow:"0 12px 35px #0002"}}>Sign-in failed: {authError}</div>}<nav className="story-nav"><a className="story-brand" href="#top"><span><Scissors/></span><b>Better Cricut Editor</b></a><div className="story-links"><a href="#workflow">How it works</a><a href="#highlights">Highlights</a><a href="#problem">Why</a><a href="#journey">Dev log</a></div>{editorAction("story-cta small","Open Editor")}</nav>
<section className="story-hero" id="top"><div className="hero-message"><span className="story-kicker"><Sparkles/> Be creative with your Cricut. No subscription. No design degree.</span><h1>Your idea.<br/><em>Your cut.</em><br/>Not another template.</h1><p>Turn AI-generated artwork into correctly sized Cricut cutouts, cake toppers and printable designs—without renting Photoshop, learning Illustrator or buying another pre-made template.</p><div className="story-actions">{editorAction("story-cta","Open the editor")}<a href="#workflow">See a real result ↓</a></div></div><div className="hero-proof"><img src="/landing/ariana-detail.png" alt="Finished Ariana is ONE gold-paper cutout mounted on clear acetate"/><span>Designed digitally.<br/>Cut from gold paper.<br/>Mounted on acetate.</span></div></section>
<section className="case-study" id="workflow"><header><span className="section-label">ONE IDEA → ONE FINISHED CAKE</span><h2>From an AI prompt to a physical Cricut project.</h2><p>No stock template was purchased. The artwork was generated, prepared at its final size, cut from selected materials and assembled on clear acetate.</p></header><div className="case-steps">
<article className="case-step prompt-step"><div className="case-label"><b>01</b><span><strong>Generate</strong><small>Nano Banana prompt + result</small></span></div><div className="nano-window"><div className="nano-head"><i>◒</i><b>Create images</b><span>Nano Banana</span></div><div className="prompt-box">cake topper out of gold paper, serif and cursive font mixed. on the white background. no cake, no stick, only the topper. high resolution. On the design it says: “Ariana is ONE”<button aria-label="Submit prompt">↑</button></div><img src="/landing/ariana-gemini.png" alt="AI generated Ariana is ONE gold cake topper artwork"/></div></article>
<article className="case-step editor-step"><div className="case-label"><b>02</b><span><strong>Prepare</strong><small>Better Cricut Editor</small></span></div><div className="case-image"><img src="/landing/ariana-editor.png" alt="Ariana is ONE design prepared as a cutout in Better Cricut Editor"/><div className="process-tags"><span>Background removed</span><span>Cutout traced</span><span>12.0 × 6.3 cm</span><span>Support stroke added</span></div></div></article>
<article className="case-step result-step"><div className="case-label"><b>03</b><span><strong>Make it real</strong><small>Gold cardstock + clear acetate</small></span></div><div className="result-images"><figure><img src="/landing/ariana-cake.jpg" alt="Finished purple Ariana is ONE birthday cake"/><figcaption>The complete cake</figcaption></figure><figure><img src="/landing/ariana-detail.png" alt="Close-up of the gold Ariana is ONE Cricut cutout on acetate"/><figcaption>The cutout and acetate detail</figcaption></figure></div></article></div></section>
<section className="highlights-v46" id="highlights"><header><span className="section-label">WHAT YOU CAN DO</span><h2>Seven practical tools between an AI image and your cutting mat.</h2></header><div className="highlight-stack">{highlights.map(([Icon,title,text],i)=><article key={title}><b>{String(i+1).padStart(2,"0")}</b><span><Icon/></span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></section>
<section className="problem-v46" id="problem"><div className="adobe-side"><span className="section-label">THE ACTUAL PROBLEM</span><div className="app-logos"><div className="ps">Ps</div><span>+</span><div className="ai">Ai</div></div><small>Photoshop + Illustrator<br/>Subscriptions + learning curve</small></div><div className="problem-copy"><h2>Cricut creativity should not begin with three subscriptions and a design degree.</h2><p>A maker should be able to create a unique image with AI, prepare the geometry, add the support a real cake topper needs and export it at the correct size—from one focused tool.</p>{editorAction("story-cta","Start creating")}</div></section>
<section className="journey-section terminal-layout" id="journey"><header><span className="section-label">THE DEVELOPMENT LOG</span><h2>43 releases built around real cutting problems.</h2><p>Each release records a concrete capability, geometry correction or workflow improvement. The log starts at the foundation and progresses toward the current vector-editing pipeline.</p><div className="terminal-legend"><span>ORDER: OLDEST → NEWEST</span><span>RELEASES: 43</span><span>STATUS: ACTIVE</span></div></header><div className="release-terminal"><div className="terminal-bar"><i/><i/><i/><span>better-cricut / CHANGELOG.log</span></div><div className="terminal-scroll">{releaseLog.map(([version,title,text])=>{const n=Number(version.split(".")[1]);return <article key={version}><div className="terminal-slicer">+---------------- {version} / {moduleFor(n)} ----------------+</div><h3>&gt; ADDED: {title.toUpperCase()}</h3><p>&gt; {text}</p>{[10,20,30,40,43].includes(n)&&<p className="terminal-milestone">&gt; MILESTONE: build {version} validated</p>}</article>})}<div className="terminal-end">+---------------- CURRENT BUILD ----------------+</div></div></div></section>
<section className="final-call"><span><Sparkles/></span><h2>Make the design yours.<br/>Then make it real.</h2><p>Better Cricut Editor is free while it is being developed.</p>{session?<a className="story-cta" href="/editor">Open the editor <ArrowRight/></a>:<button className="story-cta" onClick={signIn} disabled={busy}>Continue with Google <ArrowRight/></button>}<div ref={googleButton} className="google-hidden"/></section><footer className="story-footer"><b>Better Cricut Editor</b><span>AI artwork → cut-ready files → real projects.</span><a href="#top">Back to top ↑</a></footer></main>}
