"use client";
import {useEffect,useState} from "react";
import {ArrowRight,Check,CircleDollarSign,Image as ImageIcon,Layers3,Scissors,Sparkles,Upload,WandSparkles,X} from "lucide-react";
import type {Session} from "@supabase/supabase-js";
import {supabase} from "./lib/supabase";
import "./kreya-landing.css";

const solutions=[
  [WandSparkles,"Remove difficult backgrounds","Clean around artwork and inside lettering without spending hours erasing pixels."],
  [Scissors,"Build smooth cut shapes","Turn artwork into practical SVG cut shapes without tracing every edge by hand."],
  [Layers3,"Match print and cut borders","Add editable sticker borders and calculate the cut outline from the real outer edge."],
  [Sparkles,"Prepare personalised lettering","Create connected cake-topper lettering without hunting through fonts and joining every character yourself."],
  [ImageIcon,"Repair instead of restarting","Paint, erase, fix edges, fill enclosed gaps, separate pieces and weld them together."],
  [Check,"Export what you need","Take SVG, PNG or PDF files into the printing and cutting workflow you already use."],
] as const;
const gallery=Array.from({length:8},(_,index)=>`/landing/gallery/kreya-cake-${String(index+1).padStart(2,"0")}.jpg`);

export default function LandingPage(){
  const[session,setSession]=useState<Session|null>(null),[busy,setBusy]=useState(false),[authError,setAuthError]=useState(""),[packsOpen,setPacksOpen]=useState(false);
  useEffect(()=>{void supabase.auth.getSession().then(({data})=>setSession(data.session));const{data}=supabase.auth.onAuthStateChange((_e,next)=>setSession(next));return()=>data.subscription.unsubscribe()},[]);
  const signIn=async()=>{setAuthError("");setBusy(true);const{error}=await supabase.auth.signInWithOAuth({provider:"google",options:{redirectTo:`${window.location.origin}/editor`}});if(error){setAuthError(error.message);setBusy(false)}};
  const startButton=(className="kreya-primary",label="Start creating for free")=><a className={className} href="/editor">{label}<ArrowRight/></a>;
  return <main className="kreya-site" id="top">
    {authError&&<div className="kreya-error" role="alert">Sign-in failed: {authError}</div>}
    <nav className="kreya-nav"><a className="kreya-brand" href="#top"><img src="/landing/kreya-logo.png" alt="Kreya"/></a><div><a href="#solutions">What Kreya solves</a><a href="#how">How it works</a><a href="#real-work">Real work</a><a href="#gallery">Gallery</a><a href="#free">Free to use</a></div><span className="kreya-nav-actions">{!session&&<button onClick={()=>void signIn()} disabled={busy}>{busy?"Connecting…":"Sign in"}</button>}{startButton("kreya-primary compact",session?"Open Kreya":"Try the editor")}</span></nav>
    <section className="kreya-hero"><div className="kreya-hero-copy"><span className="kreya-eyebrow"><Sparkles/>Made for cake makers and Cricut creators</span><h1>Create cake decorations<br/><em>without the design struggle.</em></h1><p>Bring your artwork or create something new. Remove the background, prepare printable decorations and build clean cut shapes in one focused workspace.</p><div className="kreya-actions">{startButton()}<a href="#real-work">See a real result</a></div><small>Free design tools · No credit card required</small></div><figure className="kreya-hero-photo"><img src="/landing/kreya-real-cake.jpg" alt="Birthday cake decorated with printable animals and balloons prepared with Kreya"/><figcaption><b>Made with Kreya</b><span>Artwork prepared for a real cake by byAmandaSoyer</span></figcaption></figure></section>
    <section className="kreya-solutions" id="solutions"><header><span>THE PROBLEMS WE SOLVE</span><h2>Spend your time making.<br/>Not fighting design software.</h2><p>Kreya brings the repetitive preparation work into one place, so an idea can become a printable decoration or a cut-ready file.</p></header><div className="solution-grid">{solutions.map(([Icon,title,text],index)=><article key={title}><b>{String(index+1).padStart(2,"0")}</b><span><Icon/></span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="kreya-how" id="how"><header><span>ONE SIMPLE WORKFLOW</span><h2>Bring it. Prepare it. Make it.</h2></header><div><article><b>1</b><Upload/><h3>Bring or create</h3><p>Upload a PNG, JPG, WebP or SVG—or describe the new artwork you need.</p></article><article><b>2</b><WandSparkles/><h3>Prepare</h3><p>Remove backgrounds, repair edges and add the border or cut shape your project needs.</p></article><article><b>3</b><Scissors/><h3>Export and make</h3><p>Download SVG, PNG or PDF and continue with your usual printing or cutting workflow.</p></article></div></section>
    <section className="kreya-proof" id="real-work"><div className="proof-photo"><img src="/landing/kreya-real-cake.jpg" alt="Completed byAmandaSoyer birthday cake using Kreya-prepared artwork"/></div><div className="proof-copy"><span>FROM AN IDEA TO A REAL CAKE</span><h2>Not a mock-up.<br/>A finished order.</h2><p>The animals, balloons and personalised lettering on this cake were prepared for production with Kreya. The same workflow is being shaped through day-to-day custom cake work.</p><ol><li><b>Artwork prepared</b><small>Birthday animals, balloons and lettering</small></li><li><b>Edges and borders made practical</b><small>Ready for printing and accurate cutting</small></li><li><b>Used on the finished cake</b><small>A real result from byAmandaSoyer</small></li></ol><p className="partner-note">Kreya is developed in partnership with <b>byAmandaSoyer</b>, a custom cake business.</p></div></section>
    <section className="kreya-gallery" id="gallery"><header><span>MADE WITH KREYA</span><h2>Real cakes.<br/>Production-ready decorations.</h2><p>Printed artwork and personalised lettering prepared with Kreya, photographed on finished cakes by byAmandaSoyer.</p></header><div>{gallery.map((src,index)=><figure key={src}><img src={src} alt={`Finished custom cake using decorations prepared with Kreya, example ${index+1}`} loading="lazy"/></figure>)}</div></section>
    <section className="kreya-free" id="free"><div><span>THE EDITOR STAYS FREE</span><h2>Use your own artwork.<br/>Pay only when you want Kreya to create more.</h2><p>Upload, clean, edit, build borders and cut shapes, then export your work without unlocking a professional plan. Every new account also receives 20 complimentary creations—no card required.</p>{startButton()}</div><aside><div><Check/><span><b>Free design workspace</b><small>Background removal, image and SVG editing, layers and export</small></span></div><div><Sparkles/><span><b>20 complimentary creations</b><small>Try guided artwork creation before buying anything</small></span></div><div><CircleDollarSign/><span><b>Simple, permanent credit packs</b><small>Purchased creations do not expire and never renew automatically</small></span></div><button onClick={()=>setPacksOpen(true)}>See creation packs</button></aside></section>
    <section className="kreya-final"><img src="/landing/kreya-logo.png" alt=""/><h2>Your idea belongs on the cake.</h2><p>Let Kreya handle the preparation between inspiration and making.</p>{startButton()}</section>
    <footer><img src="/landing/kreya-logo.png" alt="Kreya"/><span>Independent software for makers. Kreya is not affiliated with Cricut.</span><a href="#top">Back to top ↑</a></footer>
    {packsOpen&&<div className="pack-backdrop" role="dialog" aria-modal="true" aria-label="Kreya creation packs" onPointerDown={()=>setPacksOpen(false)}><div className="pack-dialog" onPointerDown={event=>event.stopPropagation()}><button className="pack-close" onClick={()=>setPacksOpen(false)} aria-label="Close"><X/></button><span className="pack-kicker">WHEN YOUR FREE CREATIONS RUN OUT</span><h2>Get more original artwork.</h2><p>All design tools remain free. Buy a creation pack only when you want Kreya to make more artwork for you.</p><div className="pack-options"><article><small>FOR A FEW PROJECTS</small><h3>30 creations</h3><strong>Price to be confirmed</strong><p>Permanent credits. No subscription and no automatic renewal.</p><button disabled>Checkout coming soon</button></article><article className="recommended"><em>Best for regular makers</em><small>THE LARGEST STARTER PACK</small><h3>100 creations</h3><strong>$9.99</strong><p>Permanent credits for regular cake-topper and decoration work.</p><button disabled>Checkout coming soon</button></article></div><button className="continue-free" onClick={()=>setPacksOpen(false)}>Not now — continue with my own artwork</button></div></div>}
  </main>;
}
