export const releaseLog = [
  ["v0.1","A4 canvas foundation","Added a true-size A4 workspace, centimeter rulers and the first image layer model."],
  ["v0.2","Background removal","Added automatic background removal and corrected enclosed counters inside letters such as O, A and R."],
  ["v0.3","Layer workspace","Added ordered layer thumbnails, visibility controls, editable names and z-index rendering."],
  ["v0.4","Transform controls","Added corner and edge handles with proportional and single-axis resizing."],
  ["v0.5","Parametric stroke","Added outward stroke generation with editable physical width and welded intersections."],
  ["v0.6","Acetate preview","Added a translucent acetate display mode with a solid single-color export mask."],
  ["v0.7","Export pipeline","Added layer-sized SVG and PNG export plus 150 DPI A4 PDF output."],
  ["v0.8","Fixed workspace rulers","Moved rulers to the viewport edges and synchronized their scale with canvas zoom."],
  ["v0.9","Overlapping hit selection","Added repeated-click cycling for layers occupying the same canvas position."],
  ["v0.10","Physical sizing","Added decimal centimeter inputs, ratio locking and live dimension updates."],
  ["v0.11","Selection toolbar","Added contextual delete, duplicate, cut, copy and paste actions."],
  ["v0.12","Rotation system","Added live angle display, modifier-key snapping and post-rotation bounds recalculation."],
  ["v0.13","Safe-area constraints","Added configurable page margins, overflow warnings and export validation."],
  ["v0.14","Adaptive grid","Added zoom-dependent 10 cm, 1 cm, 5 mm and 1 mm grid hierarchy."],
  ["v0.15","Stroke geometry rebuild","Replaced the initial stroke implementation and recalculated bounds from generated geometry."],
  ["v0.16","Cutout color palette","Added 28 preview colors with persistent dark vector outlines."],
  ["v0.17","Acetate renderer","Improved opacity and directional edge lighting while preserving a flat export result."],
  ["v0.18","Non-destructive modifiers","Stored Remove Background, Stroke and Fill Gaps as editable layer steps."],
  ["v0.19","Gap-area analysis","Added enclosed-hole measurement and threshold-based filling for small cutout gaps."],
  ["v0.20","Bake Cutout","Added a commit operation that flattens approved modifiers into stable cutout geometry."],
  ["v0.21","SVG bounds correction","Rebuilt SVG viewBox calculation around the complete visible contour."],
  ["v0.22","Batch exports","Added separate SVG export for multiple cutouts and separate PNG export for raster selections."],
  ["v0.23","Free canvas navigation","Expanded middle-button panning at low zoom and added document recentering."],
  ["v0.24","Toolbar hierarchy","Separated creation, layout, editing, finalisation and export actions into predictable groups."],
  ["v0.25","Native shapes","Added freeform primitive and custom-shape drawing with optional Shift ratio locking."],
  ["v0.26","Visual crop frame","Replaced numeric crop controls with draggable edge and corner handles."],
  ["v0.27","Cutout erasers","Added visible brush, lasso and rectangle erasers inside Edit Cutout."],
  ["v0.28","Editor coordinate correction","Unified CSS display coordinates and source-image coordinates across popup editing tools."],
  ["v0.29","Production cleanup","Removed obsolete code, separated deployment assets and prepared the application for Cloudflare."],
  ["v0.30","Public application shell","Added the landing page, protected editor route and authentication-ready navigation."],
  ["v0.31","Google authentication","Connected Google Identity Services to Supabase sessions."],
  ["v0.32","Continuous deployment","Connected the GitHub main branch to Cloudflare automatic deployments."],
  ["v0.33","Project persistence","Added named project saving, project loading, account details and sign-out controls."],
  ["v0.34","Low-resolution preprocessing","Added supersampling and binary-mask preparation for small source images."],
  ["v0.35","Contour smoothing prototype","Tested local blur, threshold and Potrace-based contour simplification."],
  ["v0.36","Tracing pipeline revision","Adjusted curve optimisation and corner preservation after real cutout testing."],
  ["v0.37","VTracer integration","Added WebAssembly vector tracing for smoother curves and sharper corners."],
  ["v0.38","Worker timeout handling","Moved long tracing work off the UI thread and added progress timing and explicit failures."],
  ["v0.39","Local VTracer worker","Completed the browser-local tracing worker and produced stable cutout SVG geometry."],
  ["v0.40","Unified Make Cutout","Replaced the previous conversion action with the successful smooth VTracer pipeline."],
  ["v0.41","Manual vector repair","Added crop, bridge, brush and eraser tools for targeted cutout corrections."],
  ["v0.42","Local edge repair","Added a Fix the Edges brush that smooths only the selected contour corridor."],
  ["v0.43","Alpha-aware marquee selection","Changed marquee selection to test visible pixels instead of transparent layer bounds and refined responsive editor layout."],
] as const;
